---
- hosts: localhost
  gather_facts: no

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    esxi_username: "root"
    esxi_password: "VMware1!"


    SID_ESXi: 
#    - { id: S00, host: 172.0.10.13 }
#    - { id: S01, host: 172.0.10.11 }
#    - { id: S02, host: 172.0.10.12 }
#    - { id: S03, host: 172.0.10.13 }
#    - { id: S04, host: 172.0.10.11 }
#    - { id: S05, host: 172.0.10.12 }
    - { id: S09, host: 172.0.10.13 }

    LAB_Switches:
    - -SiteA
    - -SiteB
    - -SiteC

    SA_vLAN:
    - { name: -SA-Mgmt, vlan: 10 }
    - { name: -SA-vSAN, vlan: 11 }
    - { name: -SA-vMotion, vlan: 12 }
    - { name: -SA-Prod, vlan: 13 }
    - { name: -SA-Trunk, vlan: 4095 }

    SB_vLAN:
    - { name: -SB-Mgmt, vlan: 20 }
    - { name: -SB-vSAN, vlan: 21 }
    - { name: -SB-vMotion, vlan: 22 }
    - { name: -SB-Prod, vlan: 23 }
    - { name: -SB-Trunk, vlan: 4095 }

    SC_vLAN:
    - { name: -SC-Mgmt, vlan: 30 }
    - { name: -SC-vSAN, vlan: 31 }
    - { name: -SC-Trunk, vlan: 4095 }    


  tasks: 
  - name: 01. Create a Project folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      folder_name: '{{ item.id }}'
      parent_folder: '{{ parent_folder }}'
      state: present
    loop: "{{ SID_ESXi }}"  
    register: sub_folder_creation_result
    delegate_to: localhost


  - name: 02. Create Project Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ item[0].host }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: false
      switch: '{{ item[0].id + item[1]}}'
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    loop: "{{ SID_ESXi | product(LAB_Switches) | list }}"     
    delegate_to: localhost


  - name: 03. waiting vswitch creating
    wait_for:
      timeout: 10
    delegate_to: localhost


  - name: 04. Adding Portgroups to SiteA LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id + '-SiteA' }}"
      portgroup: "{{ item[0].id + item[1].name }}"
      vlan_id: '{{ item[1].vlan | int }}'
    loop: "{{ SID_ESXi | product(SA_vLAN) | list }}"      
    delegate_to: localhost


  - name: 05. Adding Portgroups to SiteB LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id + '-SiteB' }}"
      portgroup: "{{ item[0].id + item[1].name }}"
      vlan_id: '{{ item[1].vlan | int }}'
    loop: "{{ SID_ESXi | product(SB_vLAN) | list }}"      
    delegate_to: localhost


  - name: 06. Adding Portgroups to SiteC LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id + '-SiteC' }}"
      portgroup: "{{ item[0].id + item[1].name }}"
      vlan_id: '{{ item[1].vlan | int }}'
    loop: "{{ SID_ESXi | product(SC_vLAN) | list }}"      
    delegate_to: localhost
