---
- name : vSAN Mini Quickstart - Site A
  hosts: localhost

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "10.10.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    cluster_name: "SiteA"
    esxi_username: "root"
    esxi_password: "VMware1!"
    SiteA_vSAN_Cluster:
    - { host: sa-esxi-01.vclass.local, vsanip: 10.10.11.11, vmotionip: 10.10.12.11 }
    - { host: sa-esxi-02.vclass.local, vsanip: 10.10.11.12, vmotionip: 10.10.12.12 }
    - { host: sa-esxi-03.vclass.local, vsanip: 10.10.11.13, vmotionip: 10.10.12.13 }
    - { host: sa-esxi-04.vclass.local, vsanip: 10.10.11.14, vmotionip: 10.10.12.14 }
    DSwitch_SA_PG:
    - { pgname: DPG-SA-vSAN, vlan: 11 }
    - { pgname: DPG-SA-vMotion, vlan: 12 }
    - { pgname: DPG-SA-Prod, vlan: 13 }
    

  tasks: 
    - name: 01.Create Datacenter
      community.vmware.vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        state: present
      delegate_to: localhost

    - name: 02.Create Cluster
      community.vmware.vmware_cluster:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
      delegate_to: localhost

    - name: 03.Add ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
        esxi_hostname: '{{ item.host }}'
        esxi_username: 'root'
        esxi_password: 'VMware1!'
        state: present
      loop: SiteA_vSAN_Cluster
      delegate_to: localhost

    - name: 04.Create dvSwitch
      community.vmware.vmware_dvswitch:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: '{{ datacenter_name }}'
        switch: DSwitch
        version: 8.0.0
        uplink_quantity: 2
        state: present
      delegate_to: localhost

    - name: 05.Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no        
        esxi_hostname: '{{ item.host }}'
        switch_name: DSwitch
        vmnics:
          - vmnic2
          - vmnic3
        state: present
      loop: SiteA_vSAN_Cluster
      delegate_to: localhost


    - name: 06.Create Distributed Port Group for Site A
      community.vmware.vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no        
        portgroup_name: '{{ item.pgname }}'
        switch_name: DSwitch
        vlan_id: '{{ item.vlan }}'
        port_binding: static
        state: present
      loop: DSwitch_SA_PG  
      delegate_to: localhost


    - name: 07.Add vSAN vmkernel adpater
      community.vmware.vmware_vmkernel:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        esxi_hostname: '{{ item.host }}'
        dvswitch_name: DSwitch
        portgroup_name: DPG-SA-vSAN
        network:
          type: 'static'
          ip_address: '{{ item.vsanip }}'
          subnet_mask: 255.255.255.0
        state: present
        enable_vsan: yes
      loop: SiteA_vSAN_Cluster:
      delegate_to: localhost


    - name: 08.Add vMotion vmkernel port
      community.vmware.vmware_vmkernel:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        esxi_hostname: '{{ item.host }}'
        dvswitch_name: DSwitch
        portgroup_name: DPG-SA-vMotion
        network:
          type: 'static'
          ip_address: '{{ item.vmotionip }}'
          subnet_mask: 255.255.255.0
          tcpip_stack: vmotion
        state: present
        enable_vmotion: yes
      loop: SiteA_vSAN_Cluster:
      delegate_to: localhost


    - name: 09.vmoption tcp/ip stack gateway
      community.vmware.vmware_host_tcpip_stacks:
        hostname: '{{ item.host }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: no
        esxi_hostname: '{{ item.host }}'        
        vmotion:
          gateway: 10.10.12.1
      loop: SiteA_vSAN_Cluster:
      delegate_to: localhost    


    - name: 10.Enable vSAN
      community.vmware.vmware_cluster_vsan:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
        enable: true
      delegate_to: localhost
      
