---
- hosts: localhost
  gather_facts: no

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/2.vSAN"
    esxi_username: "root"
    esxi_password: "VMware1!"    
    datastore_name: "vsanDatastore"    
    templateESXiVM: "Temp-vSAN-ESXi"
    student_ID: "S00"

  - name: Configure Site-A ESXi VMs
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ parent_folder + "/" + student_ID }}"
      vm_id: "{{ item.vm_name }}"
      vm_id_type: vm_name
      vm_username: 'root'
      vm_password: 'VMware1!'
      vm_shell: /bin/sh
      vm_shell_cwd: "/tmp"
      vm_shell_args: |
        echo "Don't remove this line. Write your ESXi configuration commands below."
        esxcli system settings advanced set -o /Net/FollowHardwareMac -i 1
        sed -i 's#/system/uuid.*##' /etc/vmware/esx.conf
        esxcli network vswitch standard uplink add -u vmnic1 -v vSwitch0
        esxcli network vswitch standard portgroup set -p 'Management Network'
        esxcli network vswitch standard portgroup set -p 'VM Network'
        esxcli network ip interface ipv4 set -i vmk0 -t static -I {{ item.ipaddr }} -N 255.255.255.0 -g 10.10.10.1
        esxcli network ip route ipv4 add -n 0.0.0.0 -g 10.10.10.1
        esxcli network ip dns server add -s 10.10.10.2
        esxcli system hostname set --host {{ item.host_name }}
        esxcli system hostname set --domain vclass.local
        esxcli system ntp set -e yes -s kr.pool.ntp.org
        vim-cmd hostsvc/enable_ssh
        vim-cmd hostsvc/enable_esx_shell
        vim-cmd hostsvc/advopt/update UserVars.SuppressShellWarning long 1
        /sbin/generate-certificates
        /sbin/auto-backup.sh
      wait_for_process: True
    loop:
    - { vm_name: "{{student_ID+'-SA-ESXi-01'}}", host_name: sa-esxi-01, ipaddr: 10.10.10.11 }
    - { vm_name: "{{student_ID+'-SA-ESXi-02'}}", host_name: sa-esxi-02, ipaddr: 10.10.10.12 }
    - { vm_name: "{{student_ID+'-SA-ESXi-03'}}", host_name: sa-esxi-03, ipaddr: 10.10.10.13 }
    - { vm_name: "{{student_ID+'-SA-ESXi-04'}}", host_name: sa-esxi-04, ipaddr: 10.10.10.14 }
